# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hangman.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class HangMan(object):
    def setupUi(self, HangMan):
        HangMan.setObjectName("HangMan")
        HangMan.resize(1030, 787)
        HangMan.setStyleSheet("background-color: rgb(58, 72, 96);")
        self.verticalLayoutWidget = QtWidgets.QWidget(HangMan)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1031, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_definition = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.txt_definition.setMaximumSize(QtCore.QSize(16777215, 150))
        self.txt_definition.setStyleSheet("background-color: rgb(41, 64, 105)")
        self.txt_definition.setObjectName("txt_definition")
        self.verticalLayout.addWidget(self.txt_definition)
        self.txt_word = QtWidgets.QLabel(HangMan)
        self.txt_word.setGeometry(QtCore.QRect(10, 230, 601, 151))
        self.txt_word.setObjectName("txt_word")
        self.hangman_img = QtWidgets.QLabel(HangMan)
        self.hangman_img.setGeometry(QtCore.QRect(640, 170, 321, 291))
        self.hangman_img.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-radius: 15px;")
        self.hangman_img.setText("")
        self.hangman_img.setPixmap(QtGui.QPixmap("img/Hangman-0.png"))
        self.hangman_img.setObjectName("hangman_img")
        self.layoutWidget = QtWidgets.QWidget(HangMan)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 550, 1011, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnA = QtWidgets.QPushButton(self.layoutWidget)
        self.btnA.setMaximumSize(QtCore.QSize(60, 60))
        self.btnA.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnA.setObjectName("btnA")
        self.gridLayout.addWidget(self.btnA, 0, 0, 1, 1)
        self.btnB = QtWidgets.QPushButton(self.layoutWidget)
        self.btnB.setMaximumSize(QtCore.QSize(60, 60))
        self.btnB.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnB.setObjectName("btnB")
        self.gridLayout.addWidget(self.btnB, 0, 1, 1, 1)
        self.btnC = QtWidgets.QPushButton(self.layoutWidget)
        self.btnC.setMaximumSize(QtCore.QSize(60, 60))
        self.btnC.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnC.setObjectName("btnC")
        self.gridLayout.addWidget(self.btnC, 0, 2, 1, 1)
        self.btnD = QtWidgets.QPushButton(self.layoutWidget)
        self.btnD.setMaximumSize(QtCore.QSize(60, 60))
        self.btnD.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnD.setObjectName("btnD")
        self.gridLayout.addWidget(self.btnD, 0, 3, 1, 1)
        self.btnE = QtWidgets.QPushButton(self.layoutWidget)
        self.btnE.setMaximumSize(QtCore.QSize(60, 60))
        self.btnE.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnE.setObjectName("btnE")
        self.gridLayout.addWidget(self.btnE, 0, 4, 1, 1)
        self.btnF = QtWidgets.QPushButton(self.layoutWidget)
        self.btnF.setMaximumSize(QtCore.QSize(60, 60))
        self.btnF.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnF.setObjectName("btnF")
        self.gridLayout.addWidget(self.btnF, 0, 5, 1, 1)
        self.btnG = QtWidgets.QPushButton(self.layoutWidget)
        self.btnG.setMaximumSize(QtCore.QSize(60, 60))
        self.btnG.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnG.setObjectName("btnG")
        self.gridLayout.addWidget(self.btnG, 0, 6, 1, 1)
        self.btnH = QtWidgets.QPushButton(self.layoutWidget)
        self.btnH.setMaximumSize(QtCore.QSize(60, 60))
        self.btnH.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnH.setObjectName("btnH")
        self.gridLayout.addWidget(self.btnH, 0, 7, 1, 1)
        self.btnI = QtWidgets.QPushButton(self.layoutWidget)
        self.btnI.setMaximumSize(QtCore.QSize(60, 60))
        self.btnI.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnI.setFlat(False)
        self.btnI.setObjectName("btnI")
        self.gridLayout.addWidget(self.btnI, 0, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnJ = QtWidgets.QPushButton(self.layoutWidget)
        self.btnJ.setMaximumSize(QtCore.QSize(60, 60))
        self.btnJ.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnJ.setObjectName("btnJ")
        self.gridLayout_4.addWidget(self.btnJ, 0, 0, 1, 1)
        self.btnK = QtWidgets.QPushButton(self.layoutWidget)
        self.btnK.setMaximumSize(QtCore.QSize(60, 60))
        self.btnK.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnK.setObjectName("btnK")
        self.gridLayout_4.addWidget(self.btnK, 0, 1, 1, 1)
        self.btnL = QtWidgets.QPushButton(self.layoutWidget)
        self.btnL.setMaximumSize(QtCore.QSize(60, 60))
        self.btnL.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnL.setObjectName("btnL")
        self.gridLayout_4.addWidget(self.btnL, 0, 2, 1, 1)
        self.btnM = QtWidgets.QPushButton(self.layoutWidget)
        self.btnM.setMaximumSize(QtCore.QSize(60, 60))
        self.btnM.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnM.setObjectName("btnM")
        self.gridLayout_4.addWidget(self.btnM, 0, 3, 1, 1)
        self.btnN = QtWidgets.QPushButton(self.layoutWidget)
        self.btnN.setMaximumSize(QtCore.QSize(60, 60))
        self.btnN.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnN.setObjectName("btnN")
        self.gridLayout_4.addWidget(self.btnN, 0, 4, 1, 1)
        self.btnNe = QtWidgets.QPushButton(self.layoutWidget)
        self.btnNe.setMaximumSize(QtCore.QSize(60, 60))
        self.btnNe.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnNe.setObjectName("btnNe")
        self.gridLayout_4.addWidget(self.btnNe, 0, 5, 1, 1)
        self.btnO = QtWidgets.QPushButton(self.layoutWidget)
        self.btnO.setMaximumSize(QtCore.QSize(60, 60))
        self.btnO.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnO.setObjectName("btnO")
        self.gridLayout_4.addWidget(self.btnO, 0, 6, 1, 1)
        self.btnP = QtWidgets.QPushButton(self.layoutWidget)
        self.btnP.setMaximumSize(QtCore.QSize(60, 60))
        self.btnP.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnP.setObjectName("btnP")
        self.gridLayout_4.addWidget(self.btnP, 0, 7, 1, 1)
        self.btnQ = QtWidgets.QPushButton(self.layoutWidget)
        self.btnQ.setMaximumSize(QtCore.QSize(60, 60))
        self.btnQ.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnQ.setObjectName("btnQ")
        self.gridLayout_4.addWidget(self.btnQ, 0, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnR = QtWidgets.QPushButton(self.layoutWidget)
        self.btnR.setMaximumSize(QtCore.QSize(60, 60))
        self.btnR.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnR.setObjectName("btnR")
        self.gridLayout_5.addWidget(self.btnR, 0, 0, 1, 1)
        self.btnS = QtWidgets.QPushButton(self.layoutWidget)
        self.btnS.setMaximumSize(QtCore.QSize(60, 60))
        self.btnS.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnS.setObjectName("btnS")
        self.gridLayout_5.addWidget(self.btnS, 0, 1, 1, 1)
        self.btnT = QtWidgets.QPushButton(self.layoutWidget)
        self.btnT.setMaximumSize(QtCore.QSize(60, 60))
        self.btnT.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnT.setObjectName("btnT")
        self.gridLayout_5.addWidget(self.btnT, 0, 2, 1, 1)
        self.btnU = QtWidgets.QPushButton(self.layoutWidget)
        self.btnU.setMaximumSize(QtCore.QSize(60, 60))
        self.btnU.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnU.setObjectName("btnU")
        self.gridLayout_5.addWidget(self.btnU, 0, 3, 1, 1)
        self.btnV = QtWidgets.QPushButton(self.layoutWidget)
        self.btnV.setMaximumSize(QtCore.QSize(60, 60))
        self.btnV.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnV.setObjectName("btnV")
        self.gridLayout_5.addWidget(self.btnV, 0, 4, 1, 1)
        self.btnW = QtWidgets.QPushButton(self.layoutWidget)
        self.btnW.setMaximumSize(QtCore.QSize(60, 60))
        self.btnW.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnW.setObjectName("btnW")
        self.gridLayout_5.addWidget(self.btnW, 0, 5, 1, 1)
        self.btnX = QtWidgets.QPushButton(self.layoutWidget)
        self.btnX.setMaximumSize(QtCore.QSize(60, 60))
        self.btnX.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnX.setObjectName("btnX")
        self.gridLayout_5.addWidget(self.btnX, 0, 6, 1, 1)
        self.btnY = QtWidgets.QPushButton(self.layoutWidget)
        self.btnY.setMaximumSize(QtCore.QSize(60, 60))
        self.btnY.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnY.setObjectName("btnY")
        self.gridLayout_5.addWidget(self.btnY, 0, 7, 1, 1)
        self.btnZ = QtWidgets.QPushButton(self.layoutWidget)
        self.btnZ.setMaximumSize(QtCore.QSize(60, 60))
        self.btnZ.setStyleSheet("font: 75 20pt \"Roboto\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.btnZ.setObjectName("btnZ")
        self.gridLayout_5.addWidget(self.btnZ, 0, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)

        self.retranslateUi(HangMan)
        QtCore.QMetaObject.connectSlotsByName(HangMan)

    def retranslateUi(self, HangMan):
        _translate = QtCore.QCoreApplication.translate
        HangMan.setWindowTitle(_translate("HangMan", "Hangman"))
        self.txt_definition.setText(_translate("HangMan", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">Aquí irá la definición</span></p></body></html>"))
        self.txt_word.setText(_translate("HangMan", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">_ _ _ _ _ _ _</span></p></body></html>"))
        self.btnA.setText(_translate("HangMan", "A"))
        self.btnB.setText(_translate("HangMan", "B"))
        self.btnC.setText(_translate("HangMan", "C"))
        self.btnD.setText(_translate("HangMan", "D"))
        self.btnE.setText(_translate("HangMan", "E"))
        self.btnF.setText(_translate("HangMan", "F"))
        self.btnG.setText(_translate("HangMan", "G"))
        self.btnH.setText(_translate("HangMan", "H"))
        self.btnI.setText(_translate("HangMan", "I"))
        self.btnJ.setText(_translate("HangMan", "J"))
        self.btnK.setText(_translate("HangMan", "K"))
        self.btnL.setText(_translate("HangMan", "L"))
        self.btnM.setText(_translate("HangMan", "M"))
        self.btnN.setText(_translate("HangMan", "N"))
        self.btnNe.setText(_translate("HangMan", "Ñ"))
        self.btnO.setText(_translate("HangMan", "O"))
        self.btnP.setText(_translate("HangMan", "P"))
        self.btnQ.setText(_translate("HangMan", "Q"))
        self.btnR.setText(_translate("HangMan", "R"))
        self.btnS.setText(_translate("HangMan", "S"))
        self.btnT.setText(_translate("HangMan", "T"))
        self.btnU.setText(_translate("HangMan", "U"))
        self.btnV.setText(_translate("HangMan", "V"))
        self.btnW.setText(_translate("HangMan", "W"))
        self.btnX.setText(_translate("HangMan", "X"))
        self.btnY.setText(_translate("HangMan", "Y"))
        self.btnZ.setText(_translate("HangMan", "Z"))
